### ISSUE TITLE
no JSON object could be decoded

### ISSUE THREAD

**Issue by jopcode** [UltimateLabs/Zoom#6]
hi when i try use zoom, this give to me
```
Traceback (most recent call last):
  File "zoom.py", line 146, in <module>
    automatic(url, domain)
  File "zoom.py", line 107, in automatic
    version_vul(version[0], version[1])
  File "zoom.py", line 51, in version_vul
    jsoned = json.loads(response)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```
Any idea?

**Comment by UltimateHackers** [comment]
Thanks for reporting the issue.
Can you please provide me the target so I can reproduce it?
If you are concerned about privacy, you can mail me at s0md3v@gmail.com.
Thanks.
