### ISSUE TITLE
Error parsing wpvulndb.com response

### ISSUE THREAD

**Issue by galimba** [UltimateLabs/Zoom#7]
While executing the script I got this error and subsequent crash:

`Traceback (most recent call last):
  File "zoom.py", line 146, in <module>
    automatic(url, domain)
  File "zoom.py", line 107, in automatic
    version_vul(version[0], version[1])
  File "zoom.py", line 50, in version_vul
    response = requests.get('https://wpvulndb.com/api/v3/wordpresses/%s' % version, headers={'Authorization': 'Token token=pTs1OAhcDTJxOVjava5usL9lGpDHbIanuluU1CpoXzs'}).text
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname 'wpvulndb.com' doesn't match either of '*.sucuri.net', 'sucuri.net'`

**Comment by UltimateHackers** [comment]
Hi there,

Thanks for reporting the issue.
After looking at it, I cloned Zoom and ran it to see if I can reproduce the error but everything was perfectly fine.
But to make sure other users don't encounter the issue, I have added the `verify=False` flag into that request, which skips the checking of SSL certificates.
Let me know if the issue still exists.

Regards

**Comment by galimba** [comment]
That fixed it :-)
Thank you!

**Comment by UltimateHackers** [comment]
Feel free to report any other errors you encounter while using Zoom :)
